# Generated by Django 6.0.2 on 2026-02-12 11:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Rate used to convert from source to destination currency', max_digits=10, null=True)),
                ('converted_amount', models.DecimalField(decimal_places=2, help_text='Amount received in destination card currency', max_digits=15)),
                ('description', models.CharField(blank=True, help_text='Optional note about this transfer', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='cards.card')),
                ('to_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card Transfer',
                'verbose_name_plural': 'Card Transfers',
                'ordering': ['-created_at'],
            },
        ),
    ]
