# Generated by Django 6.0.2 on 2026-02-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtransfer',
            name='description',
            field=models.CharField(blank=True, help_text='Optional note about this transfer', max_length=255, null=True),
        ),
    ]
