# Generated by Django 6.0.2 on 2026-02-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_alter_cardtransfer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtransfer',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Rate used to convert from source to destination currency', max_digits=15, null=True),
        ),
    ]
