# Generated by Django 6.0.2 on 2026-02-09 11:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Food, Salary, Transport)', max_length=100)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], help_text='Income or Expense', max_length=10)),
                ('icon', models.CharField(choices=[('🍔', 'Food'), ('🚗', 'Transport'), ('🏠', 'Housing'), ('💰', 'Salary'), ('🎮', 'Entertainment'), ('🛒', 'Shopping'), ('💊', 'Healthcare'), ('📚', 'Education'), ('✈️', 'Travel'), ('💳', 'Bills'), ('🎁', 'Gifts'), ('👔', 'Business'), ('📱', 'Subscriptions'), ('🏋️', 'Fitness'), ('🎨', 'Hobbies'), ('📊', 'Investment'), ('🔧', 'Maintenance'), ('👨\u200d👩\u200d👧', 'Family'), ('🐕', 'Pets'), ('💅', 'Personal Care'), ('📦', 'Other')], default='📦', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, help_text='Parent category for creating subcategories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='transactions.category')),
                ('user', models.ForeignKey(blank=True, help_text='If null, this is a default system category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text="Amount in card's currenct", max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_in_user_currency', models.DecimalField(blank=True, decimal_places=2, help_text="Amount converted to user's default currency", max_digits=15, null=True)),
                ('exchange_rate_used', models.DecimalField(decimal_places=6, default=1, help_text='Exchange rate at time of transaction', max_digits=20)),
                ('title', models.CharField(help_text="Short description (e.g., 'Grocery shopping')", max_length=200)),
                ('description', models.TextField(blank=True, help_text="Additional notes or details'", null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Transaction date')),
                ('receipt_image', models.ImageField(blank=True, help_text='Upload receipt photo', null=True, upload_to='receipt/%Y/%m/%d/')),
                ('location', models.CharField(blank=True, help_text='Where the transaction occured', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(help_text='Which card/wallet was used', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='cards.card')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tag name (e.g., 'urgent', 'work', 'vacation')", max_length=50)),
                ('color', models.CharField(default='#4ECDC4', help_text='Tag color for UI (hex code)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='If null, this is a default system tag', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Tag',
                'verbose_name_plural': 'Transaction Tags',
                'db_table': 'transaction_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_transactions', to='transactions.transactiontag')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_tags', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Transaction-Tag Relation',
                'verbose_name_plural': 'Transaction-Tag Relations',
                'db_table': 'transaction_tag_relations',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'type', 'is_active'], name='categories_user_id_028087_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-date'], name='transaction_user_id_dff1f0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'type', '-date'], name='transaction_user_id_dd1053_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['card', '-date'], name='transaction_card_id_25a151_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', '-date'], name='transaction_categor_758bfc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactiontag',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='transactiontagrelation',
            unique_together={('transaction', 'tag')},
        ),
    ]
