# Generated by Django 6.0.2 on 2026-02-09 11:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Card type name (e.g., Humo, Visa, Cash)', max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Card brand logo', null=True, upload_to='card_logos/')),
                ('is_international', models.BooleanField(default=False, help_text='True for Visa/Mastercard, False for Humo/Uzcard')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Card Type',
                'verbose_name_plural': 'Card Types',
                'db_table': 'card_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Currency code (e.g., USD, UZS, EUR)', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Full currency name (e.g., Us Dollar)', max_length=50)),
                ('symbol', models.CharField(help_text="Currency symbol (e.g., $, so'm, €)", max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(help_text="Custom name for the card (e.g., 'My Main Waller')", max_length=100)),
                ('card_number_last4', models.CharField(blank=True, help_text='Last 4 digits of card number (optional, for identification)', max_length=4, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text="Current balance in card's currency", max_digits=15)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, help_text='Starting balance when card was created', max_digits=15)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name (e.g., TBC Bank, Kapitalbank)', max_length=100, null=True)),
                ('color', models.CharField(choices=[('#FF6B6B', 'Red'), ('#4ECDC4', 'Teal'), ('#45B7D1', 'Blue'), ('#FFA07A', 'Orange'), ('#98D8C8', 'Green'), ('#F7DC6F', 'Yellow'), ('#BB8FCE', 'Purple'), ('#85929E', 'Gray')], default='#4ECDC4', help_text='Color for UI display (hex code)', max_length=7)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='Default card for transactions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.cardtype')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.currency')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'db_table': 'cards',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='cards_user_id_e618c0_idx'), models.Index(fields=['user', 'is_default'], name='cards_user_id_a82651_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, help_text='Exchange rate: 1 from_currency = X to_currency', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('date', models.DateField(help_text='Date when this rate was recored')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='cards.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='cards.currency')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'db_table': 'exchange_rates',
                'ordering': ['-date', 'from_currency', 'to_currency'],
                'indexes': [models.Index(fields=['from_currency', 'to_currency', '-date'], name='exchange_ra_from_cu_2c3cda_idx')],
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
    ]
