# Generated by Django 6.0.2 on 2026-02-09 11:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Budget name (e.g., 'Weekly Food Budget')", max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Maximum amount allowed for this period', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='Budget reset period', max_length=10)),
                ('start_date', models.DateField(help_text='When this budget starts')),
                ('end_date', models.DateField(blank=True, help_text='When this budget ends (optional for recurring budgets)', null=True)),
                ('alert_threshold', models.IntegerField(default=80, help_text='Send alert when this percentage is reached (e.g., 78%)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('alert_sent', models.BooleanField(default=False, help_text='Whether alert has been sent for current period')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('exceeded', 'Exceeded')], default='active', max_length=10)),
                ('is_recurring', models.BooleanField(default=True, help_text='If true, budget resets automatically each period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Budget applies to this category', on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='transactions.category')),
                ('currency', models.ForeignKey(help_text='Currency for this budget', on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='cards.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'db_table': 'budgets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('threshold', 'Threshold Reached'), ('exceeded', 'Budget Exceeded'), ('near_end', 'Near Period End')], max_length=20)),
                ('message', models.TextField(help_text='Alert message sent to user')),
                ('spent_amount', models.DecimalField(decimal_places=2, help_text='Amount spent when alert was triggered', max_digits=15)),
                ('percentage_used', models.DecimalField(decimal_places=2, help_text='Percentage of budget used when alert was triggered', max_digits=5)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budgets.budget')),
            ],
            options={
                'verbose_name': 'Budget Alert',
                'verbose_name_plural': 'Budget Alerts',
                'db_table': 'budget_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('budget_amount', models.DecimalField(decimal_places=2, help_text='Budget limit for this period', max_digits=15)),
                ('spent_amount', models.DecimalField(decimal_places=2, help_text='Total spent during this period', max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, help_text='Amount remaining at period end', max_digits=15)),
                ('percentage_used', models.DecimalField(decimal_places=2, help_text='Percentage of budget used', max_digits=5)),
                ('was_exceeded', models.BooleanField(default=False, help_text='Whether budget was exceeded in this period')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='budgets.budget')),
            ],
            options={
                'verbose_name': 'Budget History',
                'verbose_name_plural': 'Budget Histories',
                'db_table': 'budget_history',
                'ordering': ['-period_end'],
            },
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'status'], name='budgets_user_id_6065f9_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'period', 'start_date'], name='budgets_user_id_73ee53_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetalert',
            index=models.Index(fields=['budget', '-created_at'], name='budget_aler_budget__77d1ca_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetalert',
            index=models.Index(fields=['budget', 'is_read'], name='budget_aler_budget__9429dd_idx'),
        ),
        migrations.AddIndex(
            model_name='budgethistory',
            index=models.Index(fields=['budget', '-period_end'], name='budget_hist_budget__2a5a08_idx'),
        ),
    ]
